on:
    schedule:
        - cron: '0 10 * * 2'
    pull_request:
    push:
      branches:
        - main

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: install-ubuntu
              if: ${{ matrix.os != 'windows-latest' }}
              run: |
                curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
                echo "$HOME/.moon/bin" >> $GITHUB_PATH
            - name: install-windows
              if: ${{ matrix.os == 'windows-latest' }}
              run: |
                Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
                "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

            - name: moon check
              run: |
                moon check --target wasm-gc
                moon check --target js

            - name: moon build
              run: |
                moon build --target wasm-gc
                moon build --target js